Python-Story-Valley/website/__init__.py
from flask import Flask, render_template


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'rainbow'

    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    return app

Python-Story-Valley/website/auth.py
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
import sqlite3
from sqlite3 import connect


auth = Blueprint('auth', __name__)

def usersdb():
    database = './website/sqlitedb.db'
    conn = connect(database)
    c = conn.cursor()
    createUsers = conn.execute('''CREATE TABLE IF NOT EXISTS users (userid INTEGER NOT NULL PRIMARY KEY, name TEXT NOT NULL, password TEXT NOT NULL, email TEXT NOT NULL, account INTEGER NOT NULL);''')
    return createUsers
    

def articlesdb():
    database = './website/sqlitedb.db'
    conn = connect(database)
    c = conn.cursor()
    createArticles = conn.execute('''CREATE TABLE IF NOT EXISTS articles (articleid INTEGER NOT NULL PRIMARY KEY, name TEXT NOT NULL, category TEXT NOT NULL, details TEXT NOT NULL, coverurl TEXT NOT NULL);''')
    return createArticles

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == "POST" and request.form.get('loginForm') is not None: 
        database = './website/sqlitedb.db'
        conn = connect(database)
        c = conn.cursor()
        name = request.form.get('name')
        password = request.form.get('password')
        print(name,password)
        
        loginQueryStudent = "SELECT name,password,account FROM users WHERE name ='"+name+"' AND password ='"+password+"' AND account = 0"
        c.execute(loginQueryStudent)
        resultsQueryStudent = c.fetchall()

        loginQueryTeacher = "SELECT name,password,account FROM users WHERE name ='"+name+"' AND password ='"+password+"' AND account = 1"
        c.execute(loginQueryTeacher)
        resultsQueryTeacher = c.fetchall()

        loginQueryAdmin = "SELECT name,password,account FROM users WHERE name ='"+name+"' AND password ='"+password+"' AND account = 2"
        c.execute(loginQueryAdmin)
        resultsQueryAdmin = c.fetchall()

        
        if len(resultsQueryStudent) == 1:
            print("login query found a student user called '"+name+"")
            loginStudentQuery = "SELECT name,password FROM users WHERE account = 0"
            c.execute(loginStudentQuery)
            user = request.form["loginForm"]
            session["Student"] = user
            return render_template("home.html")
        
        elif len(resultsQueryTeacher) == 1:
            print("login query found a teacher user called '"+name+"")
            loginStudentQuery = "SELECT name,password FROM users WHERE account = 0"
            c.execute(loginStudentQuery)
            user = request.form["loginForm"]
            session["Teacher"] = user
            return render_template("home.html")
        
        elif len(resultsQueryAdmin) == 1:
            print("login query found an admin user called '"+name+"")
            loginStudentQuery = "SELECT name,password FROM users WHERE account = 0"
            c.execute(loginStudentQuery)
            user = request.form["loginForm"]
            session["Admin"] = user
            return render_template("adminpanel-users.html")
        else:
            print("login query did not find the user")
        
    elif request.method == "POST" and request.form.get('registerForm') is not None:
        database = './website/sqlitedb.db'
        conn = connect(database)
        c = conn.cursor()
        name = request.form.get('name')
        password = request.form.get('password')
        email = request.form.get('email')
        account = request.form.get('account')
        print(name,password,email,account) 
        
        
        existingUserSearchQuery = "SELECT * FROM users WHERE password == 'Student'"
        createUser = conn.execute("""INSERT INTO users(name,password,email,account)VALUES (?,?,?,?)""",(name, password, email, account,)) 
        conn.commit()
        render_template("login.html") 
        return createUser
    return render_template("login.html") 

@auth.route('/logout')
def logout():
    session.pop("Student", None)
    session.pop("Teacher", None)
    session.pop("Admin", None)
    return render_template("login.html") 

@auth.route('/categories')
def categories():
    return render_template("categories.html") 

@auth.route('/articleuploader')
def articleuploader():
    if "Teacher" in session:        
        database = './website/sqlitedb.db'
        conn = connect(database)
        return render_template("articleuploader.html")     
    else:
        return render_template("login.html") 
    
@auth.route('/articleadd', methods=['GET','POST'])
def articleadd():
    if "Teacher" in session or "Admin" in session:        
        database = './website/sqlitedb.db'
        conn = connect(database)
        
        if request.form.get('addarticle') is not None:
            name = request.form.get("name)")
            category = request.form.get('category')
            details = request.form.get('details')
            coverurl = request.form.get('coverurl')
            createarticle = conn.execute("""INSERT INTO articles(name,category,details,coverurl)VALUES (?,?,?,?)""",(name,category,details,coverurl)) 
            conn.commit()
            return createarticle
        
        return render_template("articleuploader.html")     
    else:
        return render_template("login.html") 

@auth.route('/useradd', methods=['GET','POST'])
def useradd():
    if "Teacher" in session or "Admin" in session:        
        database = './website/sqlitedb.db'
        conn = connect(database)
        
        if request.form.get('addarticle') is not None:
            name = request.form.get('name')
            password = request.form.get('password')
            email = request.form.get('email')
            account = request.form.get('account')
            createuser = conn.execute("""INSERT INTO users(name,password,email,account)VALUES (?,?,?,?)""",(name, password, email, account,)) 
            conn.commit()
            return createuser
        
        return render_template("articleuploader.html")     
    else:
        return render_template("login.html") 


@auth.route('/adminpanel-users')
def adminpanelusers():
    if "Admin" in session:        
        database = './website/sqlitedb.db'
        conn = connect(database)
        return render_template("adminpanel-articles.html") 
    else: 
        return render_template("login.html")
@auth.route('/adminpanel-articles')

def adminpanelarticles():
    if "Admin" in session:        
        database = './website/sqlitedb.db'
        conn = connect(database)
        return render_template("adminpanel-articles.html") 
    else: 
        return render_template("login.html") 

Python-Story-Valley/website/views.py
from flask import Blueprint, render_template
views = Blueprint('views', __name__)


@views.route('/home')
def home():
    return render_template("home.html")

@views.route('/base')
def base():
    return render_template("base.html")

@views.route('/adminbase')
def adminbase():
    return render_template("adminbase.html")

Python-Story-Valley/website/templates/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap bundle and friends-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link href='../static/style-admins.css' rel='stylesheet'>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@300&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcd n.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <title>{% block title %}Dunseldorf{% endblock %}</title>
</head>
<body>


<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<!-- -------------------------------------------------------- [Navbar] ------------------------------------------------------------ -->
<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<section>
  <nav style="background-color: #212529;" class="navbar navbar-expand-lg navbar-dark  fixed-top">
    <div class="container">
      
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          {%if "/adminpanel-users" in request.path:%} 
            <h4>Welcome to the Admin Panel User Managemnt Page</h4>
          {%elif "/adminpanel-articles" in request.path:%}
            <h4>Welcome to the Admin Panel Articles Managemnt Page</h4>
          {%endif%}  
          
          <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
              
                <li class="nav-item active">
                  <a class="nav-link" href="./adminpanel-users">Users</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="./adminpanel-articles">Articles</a>
                </li>
                <li class="nav-item">
                  <a class='nav-link' href='./logout'>Logout</a>  
                </li>
            </ul>
          </div>
      </div>
  </nav>
</section>

<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<!-- -------------------------------------------------------- [CONTENT] ------------------------------------------------------------ -->
<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
{%block content%}
{%endblock%}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

Python-Story-Valley/website/templates/adminpanel-articles.html
{% extends "adminbase.html" %} {% block title %}AP - Articles{% endblock %}


{%block content%}

<section>
    <table border=1>
    <tr>
    <th>Article_Name</th>
    <th>Category</th>
    <th>Details</th>
    <th>Cover Url</th>
    </tr>
    
    <form action="{{ url_for('auth.articleadd')}}" method='POST' enctype='multipart/form-data'>
    <tr>
    <td><input type='text' name='name' value ='' placeholder='Name your Article'>  </td>
    <td>  
    <select name='category'>
      <option value='Scottish'>    Scottish     </option>
      <option value='English'>     English      </option>
      <option value='French'>      French       </option>
    </select>
    </td>
    <td><textarea              name='details'      value ='' placeholder='Place your Text Here' ncols='32' rows='2'></textarea> </td>
    <td><input type='text'     name='coverurl'    value ='' placeholder='Add your Cover Url'></td>
    <td><input type='submit'   name='addarticle' id='panel-button'  value ='Add'>  </td>
    </form>
    </tr>
    
    </table>
    
    </section>



{%endblock%}

Python-Story-Valley/website/templates/adminpanel-users.html
{% extends "adminbase.html" %} {% block title %}AP - Users{% endblock %}


{%block content%}

<section>
<table>
    <tr>
    <th>Name</th>
    <th>Password</th>
    <th>E-Mail</th>
    <th>Account Type</th>
    </tr>;
    <form action="{{ url_for('auth.useradd')}}" method='POST' enctype='multipart/form-data'>
    <tr>
    <td><input type='text'   name='name'          value =''></td>
    <td><input type='text'   name='password'      value =''></td>
    <td><input type='text'   name='email'        value =''></td>
    <td><input type='number' name='account'       value =''></td>
    <td><input type='submit' name='adduser' id='panel-button'  value ='Add'></td>
    </form>
    </tr>
    </table>
</section>

{%endblock%}

Python-Story-Valley/website/templates/articleuploader.html
{% extends "base.html" %} {% block title %}Article Uploader{% endblock %}


{%block content%}

<section>
    <table border=1>
    <tr>
    <th>Article_Name</th>
    <th>Category</th>
    <th>Details</th>
    <th>Cover Url</th>
    </tr>
    
    <form action="{{ url_for('auth.articleadd')}}" method='POST' enctype='multipart/form-data'>
    <tr>
    <td><input type='text' name='name' value ='' placeholder='Name your Article'>  </td>
    <td>  
    <select name='category'>
      <option value='Scottish'>    Scottish     </option>
      <option value='English'>     English      </option>
      <option value='French'>      French       </option>
    </select>
    </td>
    <td><textarea              name='details'      value ='' placeholder='Place your Text Here' ncols='32' rows='2'></textarea> </td>
    <td><input type='text'     name='coverurl'    value ='' placeholder='Add your Cover Url'></td>
    <td><input type='submit'   name='addarticle' id='panel-button'  value ='Add'>  </td>
    </form>
    </tr>
    
    </table>
    
    </section>


{%endblock%}

Python-Story-Valley/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap bundle and friends-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<link href='../static/style-seniors.css' rel='stylesheet'>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Roboto:wght@300&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcd n.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <title>{% block title %}Dunseldorf{% endblock %}</title>
</head>
<body>


<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<!-- -------------------------------------------------------- [Navbar] ------------------------------------------------------------ -->
<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<section>
  <nav style="background-color: #FBFBFB;" class="navbar navbar-expand-lg navbar-dark  fixed-top">
    <div class="container">
      
          <a class="logo" href="./home"><img src="http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/img/Story-Valley-Colour-Logo.png" alt="Profile Image" width="100" height="50"></a>
          {%if "Student"in session:%} 
            <h4>Student is logged in</h4>
          {%elif "Teacher" in session:%}
            <h4>Teacher is logged in</h4>
          {%elif "Admin" in session%}
            <h4>Admin is logged in</h4> 
          {%endif%}  

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
    
          <div class="collapse navbar-collapse justify-content-end" id="navbarResponsive">
            <ul class="navbar-nav ms-auto">
              
                <li class="nav-item active">
                  <a class="nav-link" href="./home">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="./categories">Categories</a>
                </li>
                {%if "Teacher" in session%}
                <li class="nav-item">
                  <a class="nav-link" href="./articleuploader">Article Uploader</a>
                </li>
                {%endif%}
                {%if "/home" in request.path%}
                <li class="nav-item">
                  <a class="nav-link" href="#about">About</a>
                </li>
                {%endif%}
                <li class="nav-item">
                  <a class="nav-link" href="#footer">Contact</a>
                </li>
                <li class="nav-item">
                  {%if "Student" in session or "Teacher" in session or "Admin" in session:%} 
                    <a class='nav-link' href='./logout'>Logout</a>            
                  {% else %}
                    <a class='nav-link' href='./login'>Login / Register</a>
                  {%endif%}
                </li>
            </ul>
          </div>
      </div>
  </nav>
</section>

<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<!-- -------------------------------------------------------- [CONTENT] ------------------------------------------------------------ -->
<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
{%block content%}
{%endblock%}


<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<!-- -------------------------------------------------------- [Footer] ------------------------------------------------------------ -->
<!-- ------------------------------------------------------------------------------------------------------------------------------ -->

<footer id="footer" class="footer-distributed">

  <div class="footer-left">
  <h3 style="padding-bottom: 30px;">Story Valley |<span> | Bridging Cultures</span></h3>
  <div class="footer-center ">
  <div style="padding-bottom: 20px; padding-right: 10px;">
    <i class="fa fa-map-marker"></i>
    <p style=" opacity: 80%;"> EH52 Broxburn - Scotland</p>
  </div>
  <div style="padding-bottom: 20px; padding-right: 50px;">
    <i class="fa fa-phone"></i>
    <p style=" opacity: 80%;">+44 07 309 714 397</p>
  </div>
  <div style="padding-left: 60px;">
    <i class="fa fa-envelope"></i>
    <p style=" opacity: 80%;"><a href="mailto:support@company.com">thisismypazzword@gnmail.com</a></p>
  </div>
  </div>
  
  <div class="footer-right">
  
  <p class="footer-company-about" style="color: var()--text-color; padding-bottom: 20px;">
    <span>That's About It</span>
    Thanks for stopping by and feel free to contact us on all social that you see below<br>
    We hope you found what you were looking for, if not, please let us know!
  </p>

  <a class="pb-2" target="_blank" href="http://webdev.edinburghcollege.ac.uk/~HNDWEBMR9/Story-Valley-Website/php/privacy-policy.php">Privacy Policy</a>
  
  <div class="footer-icons">
    <a href="https://www.facebook.com/luca.pae/" target="_blank"><i class="fa fa-facebook"></i></a>
    <a href="https://uk.linkedin.com/in/lawrence-luca-pae-b252b7187" target="_blank"><i class="fa fa-linkedin"></i></a>
    <a href="https://github.com/L-L-P-bandana?tab=repositories" target="_blank"><i class="fa fa-github"></i></a>
  </div>
  </div>
  
</footer>



<!-- Cookie Policy -->
<script src="https://cdn.websitepolicies.io/lib/cookieconsent/cookieconsent.min.js" defer></script><script>window.addEventListener("load",function(){window.wpcc.init({"colors":{"popup":{"background":"#222222","text":"#ffffff","border":"#fde296"},"button":{"background":"#fde296","text":"#000000"}},"position":"bottom","padding":"large","content":{"href":"https://www.cookiepolicygenerator.com/live.php?token=6XCGXmtmdEvL51xvS3PR02QVFEs6p2fj","message":"This website uses cookies to get the best out of the website"},"margin":"none","transparency":"5"})});</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

Python-Story-Valley/website/templates/categories.html
{% extends "base.html" %} {% block title %}Article Uploader{% endblock %}


{%block content%}

<section>
    <div class='col-md-12 d-flex justify-content-around'>
        <div class='card col-md-3'>
        <div class='card-body'>
            <form action='#' method='POST'>
            <h5 class='card-part card-title d-flex justify-content-center'>Blondine</h5>   
            <h6 class='card-part card-subtitle mb-2 text-muted d-flex justify-content-center'>  
                <img src='./static/img/blondine.jpg' alt='image url not found' class='image-responsive img-thumbnail' style='max-height: 200px max-width=200px'>
            </h6>	
            <p class='card-part card-text'>
                There was once a king called Benin. He was good and all the world loved him; he was just and the wicked feared him. His wife, the Queen Doucette, was also good, and much beloved.This happy pair had a daughter called the Princess Blondine, because of her superb fair hair, and she was as amiable and charming as her father the king and her mother the queen.
            </p>
            <a class= "btn ml-2 d-flex justify-content-center" input type="submit" name="Submit" id="panel-button" value ="Submit" href="#">Read Now</a>
            </form>
        </div>   
        </div>  

        <div class='card col-md-3'>
        <div class='card-body'>
            <form action='#' method='POST'>
            <h5 class='card-part card-title d-flex justify-content-center'>Lament</h5>   
            <h6 class='card-part card-subtitle mb-2 text-muted d-flex justify-content-center'>  
                <img src='./static/img/lament.jpg' alt='image url not found' class='image-responsive img-thumbnail' style='max-height: 200px max-width=200px'>
            </h6>	
            <p class='card-part card-text'>
                One day it was announced to the king, that all his subjects demanded that he should marry again in order to have a son who should reign after him. He refused at first but finally yielded to the pressing desires of his people and said to his minister Leger:"My dear friend, my subjects wish me to marry again but my heart is so sad because of the death of my cherished queen Doucette that I cannot undertake the task of seeking another wife.
            </p>
            <a class= "btn ml-2 d-flex justify-content-center" input type="submit" name="Submit" id="panel-button" value ="Submit" href="#">Read Now</a>
            </form>
        </div>   
        </div>    

        <div class='card col-md-3'>
        <div class='card-body'>
            <form action='#' method='POST'>
            <h5 class='card-part card-title d-flex justify-content-center'>The Lost Queen</h5>   
            <h6 class='card-part card-subtitle mb-2 text-muted d-flex justify-content-center'>  
                <img src='./static/img/the-lost-queen.jpg' alt='image url not found' class='image-responsive img-thumbnail' style='max-height: 200px max-width=200px'>
            </h6>	
            <p class='card-part card-text'>
                At last he arrived at the kingdom of the monarch Turbulent, who had a lovely daughter, bright, winning and apparently good. Leger found her so charming, that he asked her hand in marriage for his king Benin, without sufficiently inquiring into her real character.            </p>
            <a class= "btn ml-2 d-flex justify-content-center align-items-end" input type="submit" name="Submit" id="panel-button" value ="Submit" href="#">Read Now</a>
            </form>
        </div>   
        </div>   
    </div>        
  </div>
</section>


{%endblock%}

Python-Story-Valley/website/templates/login.html
{% extends "base.html" %} {% block title %}Login / Register{% endblock %}

{%block content%}
<!-- --------------------------------------------------------------------------------------------------------------------------- -->
<!-- ------------------------------------------------------ [Registration / Login Form] ---------------------------------------- -->
<!-- --------------------------------------------------------------------------------------------------------------------------- -->

<section>
  <div class="row" style="padding-top: 40px;">
    <div class="col-md-6 mx-auto p-0">
        <div class="card card-login">
            <div class="login-box">
                <div class="login-snip"> <input id="tab-1" type="radio" name="tab" class="sign-in" checked><label for="tab-1" class="tab">Login</label> <input id="tab-2" type="radio" name="tab" class="sign-up"><label for="tab-2" class="tab">Sign Up</label>
                    <div class="login-space">
                        <form method="POST" class="login" action="{{ url_for('auth.login')}}">
                            <div class="group"> <label for="user" class="label">Username</label> <input name="name" id="Username" type="text" class="input" placeholder="Enter your username"> </div>
                            <div class="group"> <label for="pass" class="label">Password</label> <input name="password" id="Password" type="password" class="input" data-type="password" placeholder="Enter your password"> </div>
                            <div class="group"> <input id="check" type="checkbox" class="check" checked> <label class="checkbox" for="check"><span class="icon"></span> Keep me Signed in</label> </div>
                            <div class="group"> <input name="loginForm" type="submit" class="button" value="login"> </div>
                            <div class="hr"></div>
                            <div class="foot"> <a href="#">Forgot Password?</a> </div>
                        </form>
                        <form method="POST" class="sign-up-form" action="{{ url_for('auth.login')}}">
                            <div class="group"> <label for="user" class="label">Username       </label> <input name="name" id="user" type="text"      class="input" placeholder="Create your Username" required="required"> </div>
                            <div class="group"> <label for="pass" class="label">Password       </label> <input name="password" id="pass" type="password"  class="input" data-type="password" placeholder="Create your password" required="required"> </div>
                            <div class="group"> <label for="pass" class="label">Email Address  </label> <input name="email"   id="pass" type="text"      class="input" placeholder="Enter your email address" required="required"> </div>                            <div class="group"> <label for="user" class="label">Account Type   </label> 
                            <input type="radio" id="student" name="account" value="0">   <label for="student">Student</label> <br> 
                            <input type="radio" id="teacher" name="account" value="1">   <label for="teacher">Teacher</label> <br> <br>
                            
                            <div class="group"> <input name="registerForm"type="submit" class="button" value="register"> </div>
                            
                            <div class="hr"></div>
                            <div class="foot"> <label for="tab-1">Already A Member?</label> </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
{%endblock%}